name: C++ CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                sudo apt update 
                sudo apt install -y g++ cmake qt5-qmake qtbase5-dev

            - name: Configure CMake
              run: | 
                cmake -B build -S . -DCMAKE_CXX_STANDARD=17

            - name: Build
              run: |
                cmake --build build

            - name: Run Tests
              run: |
                cd build && ctest --verbose